project_id = "kuxpsfxkumbfuqsvcucx"

[functions.chat-ai]
verify_jwt = false

[functions.service-chat]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.codef-card]
verify_jwt = false

[functions.codef-bank]
verify_jwt = false
